version: '3.9'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  migration:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "migrate"]
    environment:
      - "DJANGO_SETTINGS_MODULE=src.settings.local-docker"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  load_fixtures:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "loaddata", "products/fixture.json"]
    environment:
      - "DJANGO_SETTINGS_MODULE=src.settings.local-docker"
    volumes:
      - .:/usr/src/app
    depends_on:
      - migration
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - "DJANGO_SETTINGS_MODULE=src.settings.local-docker"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
      - load_fixtures
